/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface client {
  'clientID': string;
  'created'?: Date | null;
  'description': string;
  'title': string;
}
export interface kysely_migration {
  'name': string;
  'timestamp': string;
}
export interface kysely_migration_lock {
  'id': string;
  'is_locked'?: number;
}

export interface Database {
  "client": client
  "kysely_migration": kysely_migration
  "kysely_migration_lock": kysely_migration_lock
}